### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET localhost:8080/question/allQuestions

###
POST localhost:8080/question/add
Content-Type: application/json

{
  "questionTitle": "Which of the following is NOT a relational database?",
  "option1": "MySQL",
  "option2": "PostgreSQL",
  "option3": "MongoDB",
  "option4": "Oracle",
  "rightAnswer": "MongoDB",
  "difficultylevel": "Medium",
  "category": "Computer Science"
}

###
POST localhost:8080/question/getQuizQuestions
Content-Type: application/json

[1,2,3]


